#!/bin/sh

set -e


# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p indicator-china-weather /usr/share/indicator-china-weather -V 2.6-
fi

# End automatically added section


echo "Installing indicator-specific icons..."
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/indicator-china-weather/data/media/icon_china_weather.png weather-indicator
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/indicator-china-weather/data/media/icon_unknown_condition.png weather-indicator-unknown
xdg-icon-resource install --theme hicolor --novendor --size 22 /usr/share/indicator-china-weather/data/media/icon_connection_error.png weather-indicator-error
